/**
 * GENERATED by scripts/gen-backend-index.mjs — do not edit.
 * 2 backend manifest(s) in directory-name order (picker order):
 * claude, codex.
 *
 * `pnpm compile` refreshes this file: commit the result. It is checked in
 * because the CI test groups restore the build artifact instead of compiling, and
 * the registry imports it from `src/` (see the generator for the whole story).
 */
import type { BackendEntry } from '../agent/backend-manifest.js'
import { manifest as claudeManifest } from '../backends/claude/manifest.js'
import { manifest as codexManifest } from '../backends/codex/manifest.js'

export const GENERATED_BACKENDS: readonly BackendEntry[] = [
  { manifest: claudeManifest, load: () => import('../backends/claude/index.js') },
  { manifest: codexManifest, load: () => import('../backends/codex/index.js') },
]
